# Generated by Django 5.2.6 on 2025-09-17 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='validation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=222)),
                ('age', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=220)),
            ],
        ),
    ]
